### ISSUE TITLE
refactor: PDF and HTML reports should use NotoSansSC

### ISSUE THREAD

**Issue by christophbuehler** [s1seven/schema-tools#150]
# Description

In order to support character sets other than latin in the PDFs, we will be switching to [NotoSans](https://fonts.google.com/noto/fonts) for the creation of reports. For now this would be [NotoSansSC](https://fonts.google.com/noto/specimen/Noto+Sans+SC?subset=chinese-simplified&query=noto) to support simplified chinese. The styles should be adjusted accordingly.

_NotoSans (right) uses more vertical space than Lato:_
![image](https://user-images.githubusercontent.com/4547315/170265204-de03313d-e5e8-4b3c-86d8-bde1a2bf07a6.png)

## ToDo
- [ ] Adjust the report styles to accommodate the rendering of NotoSans in a more compact matter.
- [x] [Add section for Disclaimer](https://github.com/thematerials-network/CoA-schemas/issues/42)
- [x] [Reduce font size for Disclaimer](https://github.com/thematerials-network/CoA-schemas/issues/43)
- [x] Add "This is a computer-generated document. No signature is required."
- [x] Add link to CoA Website
- [x] Add Link to verification website
- [x] Update "Powered by S1Seven"

## Follow-up
- [x] [Adjust PDF rendering to use NotoSansSC as a default font.](https://github.com/thematerials-network/CoA-schemas/issues/38)
- [ ] Adjust default font of HTML rendering..

## Later work
- [ ] Facilitate rendering of different type sets like Japanese or Arabic.
